language: python

python:
    - 3.4
    - 3.5
    - 3.6
    - pypy3

env:
    - DJANGO="django>=1.11,<2"
    - DJANGO="django>=2.0,<2.1"
    - DJANGO="django>=2.1,<2.2"

install:
    - pip install ${DJANGO}
    - pip install -r requirements.txt
    - pip install -r test_requirements.txt

script:
    - python manage.py test

matrix:
  include:
    - python: 2.7
      env: DJANGO="django>=1.11,<2"
    - python: pypy
      env: DJANGO="django>=1.11,<2"
    - python: 3.7
      dist: xenial
      sudo: true
      env: DJANGO="django>=1.11.17,<2"
    - python: 3.7
      dist: xenial
      sudo: true
      env: DJANGO="django>=2.0,<2.1"
    - python: 3.7
      dist: xenial
      sudo: true
      env: DJANGO="django>=2.1,<2.2"
  exclude:
    - python: 3.4
      env: DJANGO="django>=2.1,<2.2"

